include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    implicit_dynamic_method: ignore
    implicit_dynamic_parameter: ignore
    implicit_dynamic_type: ignore
  exclude:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/*.gr.dart"
  - "**/*.iconfig.dart"
  - "**/*.config.dart"

